AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ChannelName:
    Type: String
    Description: Enter the channel name
  IamRole:
    Type: String
    Description: Enter the IAM role ARN
  ChannelID:
    Type: String
    Description: Enter the channel ID
  WorkspaceID:
    Type: String
    Description: Enter the workspace ID
  TopicARN:
    Type: String
    Description: Enter the Topic ARN

Resources:
  Chatbot:
    Type: 'AWS::Chatbot::SlackChannelConfiguration'
    Properties:
      ConfigurationName: !Ref ChannelName
      IamRoleArn: !Ref IamRole
      LoggingLevel: ERROR
      SlackChannelId: !Ref ChannelID
      SlackWorkspaceId: !Ref WorkspaceID
      SnsTopicArns: 
        - !Ref TopicARN
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 089bf9d6-a2a9-4459-ae95-69eb19129961
